### ISSUE TITLE
Failed to build with GCC 13 since commit 5625edec7bb

### ISSUE THREAD

**Issue by HouLiXieBuRou** [Esri/lerc#253]
I am building under the latest repository and encountering the error: 
```/root/lerc/src/LercLib/fpl_Compression.cpp: In static member function ‘static size_t LercNS::fpl_Compression::compress_buffer(const char*, size_t, char**, bool)’:
/root/lerc/src/LercLib/fpl_Compression.cpp:75:26: error: ‘UINT_MAX’ was not declared in this scope
   75 |           return (size_t)UINT_MAX + 1;
      |                          ^~~~~~~~
/root/lerc/src/LercLib/fpl_Compression.cpp:30:1: note: ‘UINT_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
   29 | #include <cstring>
  +++ |+#include <climits>
   30 | 
```
 My architecture is amd64, debian sid.

**Comment by tmaurer3** [comment]
@HouLiXieBuRou  Thanks for reporting it!
